name: Setup Rclone action
description: Setup/Install Rclone for GitHub Actions
branding:
  icon: cloud
  color: blue
inputs:
  rclone_config:
    description: Rclone config file encoded in base64
    required: true
    
runs:
  using: composite
  steps:
    - name: Download Rclone for Linux
      if: runner.os == 'Linux'
      shell: bash
      working-directory: ${{ runner.temp }}
      run: $GITHUB_ACTION_PATH/download-scripts/Linux.sh
      
    - name: Download Rclone for Windows
      if: runner.os == 'Windows'
      shell: pwsh
      working-directory: ${{ runner.temp }}
      run: '& $env:GITHUB_ACTION_PATH\download-scripts\Windows.ps1'
      
    - name: Download Rclone for macOS
      if: runner.os == 'macOS'
      shell: bash
      working-directory: ${{ runner.temp }}
      run: $GITHUB_ACTION_PATH/download-scripts/macOS.sh
      
    - name: Install Rclone on tool cache
      uses: AnimMouse/tool-cache@v1
      with:
        folder_name: Rclone
        
    - name: Sign in to Rclone using Rclone config on Unix-like
      if: runner.os == 'Linux' || runner.os == 'macOS'
      shell: bash
      env:
        rclone_config: ${{ inputs.rclone_config }}
      run: $GITHUB_ACTION_PATH/sign-in-scripts/Unix-like.sh
      
    - name: Sign in to Rclone using Rclone config on Windows
      if: runner.os == 'Windows'
      shell: pwsh
      env:
        rclone_config: ${{ inputs.rclone_config }}
      run: '& $env:GITHUB_ACTION_PATH\sign-in-scripts\Windows.ps1'