name: Test setup-rclone
on:
  push:
    paths:
      - action.yaml
      - scripts/**
      - .github/workflows/test.yaml
      
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    steps:
      - name: Setup Rclone using setup-rclone
        uses: AnimMouse/setup-rclone@main
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}
          
      - name: Test Rclone by listing remotes
        run: rclone listremotes
        
      - name: Test Rclone by listing test remote
        run: 'rclone ls setup-gdrive-test:'