name: Test setup-rclone/update-config
on:
  push:
    paths:
      - update-config/action.yaml
      - .github/workflows/test-update-config.yaml
  pull_request:
    paths:
      - update-config/action.yaml
      - .github/workflows/test-update-config.yaml
      
jobs:
  test-unix-like:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        
    steps:
      - name: Get past secret value (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: echo $rclone_config | base64 -d
        env:
          rclone_config: ${{ secrets.RCLONE_CONFIG_UPDATE_TEST_UBUNTU }}
          
      - name: Get past secret value (macOS)
        if: matrix.os == 'macos-latest'
        run: echo $rclone_config | base64 -d
        env:
          rclone_config: ${{ secrets.RCLONE_CONFIG_UPDATE_TEST_MACOS }}
          
      - name: Generate new secret value
        run: |
          mkdir -p ~/.config/rclone
          rclone_config=$RANDOM
          echo $rclone_config
          echo $rclone_config > ~/.config/rclone/rclone.conf
          
      - name: Update Rclone config using setup-rclone/update-config (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        uses: AnimMouse/setup-rclone/update-config@main
        with:
          rclone_config_name: RCLONE_CONFIG_UPDATE_TEST_UBUNTU
          token: ${{ secrets.GH_PAT }}
          
      - name: Update Rclone config using setup-rclone/update-config (macOS)
        if: matrix.os == 'macos-latest'
        uses: AnimMouse/setup-rclone/update-config@main
        with:
          rclone_config_name: RCLONE_CONFIG_UPDATE_TEST_MACOS
          token: ${{ secrets.GH_PAT }}
          
  test-windows:
    runs-on: windows-latest
    steps:
      - name: Get past secret value
        run: '[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($env:rclone_config))'
        env:
          rclone_config: ${{ secrets.RCLONE_CONFIG_UPDATE_TEST_WINDOWS }}
          
      - name: Generate new secret value
        run: |
          New-Item $env:APPDATA\rclone -ItemType Directory
          $rclone_config = Get-Random
          $rclone_config
          [IO.File]::WriteAllBytes("$env:APPDATA\rclone\rclone.conf", [Text.Encoding]::UTF8.GetBytes($rclone_config))
          
      - name: Update Rclone config using setup-rclone/update-config
        uses: AnimMouse/setup-rclone/update-config@main
        with:
          rclone_config_name: RCLONE_CONFIG_UPDATE_TEST_WINDOWS
          token: ${{ secrets.GH_PAT }}